name: this is the scan

on:
  pull_request:
    paths:
      - '*'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    name: scan
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: hello world
        run: echo "hello world"

      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master

      - name: also verify this way
        run: git show --show-signature
