name: this is the scan

on:
  pull_request:
    paths:
      - '*'

scan:
  runs-on: self-hosted
  name: scan

  steps:
  - uses: actions/checkout@v3
    with:
      fetch-depth: 0
      ref: ${{ github.head_ref }}

  - name: trufflehog-actions-scan
    uses: edplato/trufflehog-actions-scan@master
