name: this is the scan

on:
  pull_request:
    paths:
      - '*'
  workflow_dispatch:

jobs:
  runs-on: ubuntu-latest
  name: scan

  steps:
  - uses: actions/checkout@v3
    with:
      fetch-depth: 0
      ref: ${{ github.head_ref }}

  - name: hello world
    run: echo "hello world"
